spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123 
            client-secret: 123
            scope: 
              - openid
              - profile
              - email

app:
  oauth:
    default-password: 123