import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 110,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 14,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#666",
    marginTop: 2,
  },
  addEventButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#628141",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    gap: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  addEventButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  petFilterContainer: {
    marginBottom: 14,
  },
  petChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    marginRight: 8,
    gap: 6,
  },
  petChipActive: {
    backgroundColor: "#628141",
    borderColor: "#628141",
  },
  petChipText: {
    fontSize: 13,
    color: "#555",
    fontWeight: "600",
  },
  petChipTextActive: {
    color: "#fff",
    fontWeight: "bold",
  },
  statusTabs: {
    flexDirection: "row",
    backgroundColor: "rgba(98, 129, 65, 0.12)",
    borderRadius: 12,
    padding: 3,
    marginBottom: 16,
  },
  statusTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 9,
  },
  statusTabActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  statusTabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666",
  },
  statusTabTextActive: {
    color: "#628141",
    fontWeight: "bold",
  },
  dateGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 6,
    gap: 6,
  },
  dateGroupText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#444",
  },
  dateDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "#ddd",
    marginLeft: 6,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#eee",
  },
  cardCompleted: {
    opacity: 0.65,
    backgroundColor: "#f9f9f9",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  categoryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  categoryIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#333",
  },
  timeBadge: {
    backgroundColor: "#f0f4ec",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  timeText: {
    fontSize: 12,
    color: "#4a6b31",
    fontWeight: "700",
  },
  cardBody: {
    marginBottom: 8,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#222",
    marginBottom: 4,
  },
  eventTitleCompleted: {
    textDecorationLine: "line-through",
    color: "#888",
  },
  eventNotes: {
    fontSize: 13,
    color: "#666",
    marginBottom: 4,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  petTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fbf3ea",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  petTagText: {
    fontSize: 12,
    color: "#ea9b56",
    fontWeight: "600",
  },
  cardActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  completeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 45,
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#444",
    marginTop: 14,
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#777",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  createEmptyButton: {
    marginTop: 18,
    backgroundColor: "#ea9b56",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  createEmptyButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "88%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: "bold",
    color: "#333",
  },
  inputGroup: {
    marginBottom: 14,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#444",
    marginBottom: 6,
  },
  input: {
    backgroundColor: "#F7F7F6",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: "#333",
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#F7F7F6",
    gap: 6,
  },
  categoryItemActive: {
    borderColor: "#628141",
    backgroundColor: "#edf4e8",
  },
  categoryItemText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#555",
  },
  categoryItemTextActive: {
    color: "#4a6b31",
    fontWeight: "bold",
  },
  rowInputs: {
    flexDirection: "row",
    gap: 12,
  },
  flexHalf: {
    flex: 1,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
    marginBottom: 20,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
  },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#666",
  },
  submitBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#ea9b56",
    alignItems: "center",
  },
  submitBtnText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#fff",
  },
});
